name: Good Morning Bot

on:
  schedule:
    # ساعت ۹ صبح به وقت ایران = ۵:۳۰ صبح UTC
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          MAEDE_CHAT_ID: ${{ secrets.MAEDE_CHAT_ID }}
        run: python main.py
